// The two locale dictionaries the shell hands every surface as the `copy` prop.

export const copyByLocale = {
  en: {
    nav: {
      Today: 'Today',
      Plan: 'Plan',
      Broadcast: 'Broadcast',
      Commercial: 'Commercial',
      Sources: 'Sources',
      Governance: 'Governance',
      History: 'History',
      Model: 'Company model',
      Overview: 'Overview',
      Optimizer: 'Optimizer',
      Schedule: 'Schedule',
      Inventory: 'Inventory',
      'Break Library': 'Break Library',
      Campaigns: 'Campaigns',
      Forecasts: 'Forecasts',
      Calendar: 'Events calendar',
      Reports: 'Reports',
      Data: 'Data',
      Advertisers: 'Advertisers',
      Agencies: 'Agencies',
      Pricing: 'Pricing',
      Overrides: 'Overrides',
      Assistant: 'Mabat, operations assistant',
      Versions: 'Restore changes',
      Settings: 'Settings',
    },
    workspace: 'Revenue operations',
    operatorRole: 'Revenue Ops',
    optimizer: 'Optimizer',
    scenario: 'Scenario',
    scenarios: ['Balanced', 'Revenue priority', 'Retention guardrail'],
    compare: 'Compare',
    liveApi: 'Live API',
    checkingApi: 'Checking the API',
    snapshot: 'API unreachable',
    partialData: 'Some data failed to load',
    data: 'Data',
    dataUpdated: 'Updated',
    refresh: 'Refresh',
    notifications: 'Notifications',
    runOptimization: 'Run Optimization',
    loading: 'Loading Kairos workspace',
    apiUnavailable: 'API unavailable. Some data could not be loaded.',
    // The headline speaks in the operator's working horizon: the planning week
    // (summary.week from the API). Exact dates are disclosed in the tile sub
    // line and under the strip from the basis fields.
    metrics: ['Weekly projected revenue', 'Break viewer retention', 'Weekly ad minutes', 'Retention risk'],
    risk: { High: 'High', Medium: 'Medium', Low: 'Low', Unknown: 'Unknown' },
    toolbar: ['Grid View', 'Timeline', 'Daypart', 'Inventory', 'Programs', 'Breaks', 'Metrics'],
    canvas: 'Broadcast planning canvas',
    channelProgram: 'Channel / Program',
    selectedBreak: 'Selected break',
    pending: 'Pending',
    approved: 'Approved',
    detail: ['Plan revenue', 'Plan retention', 'Duration', 'Sponsorships'],
    guardrails: 'Guardrails',
    recommendation: 'Recommendation',
    approve: 'Approve',
    reject: 'Reject',
    applySimilar: 'Approve similar',
    export: 'Export',
    exportOptions: ['Break detail', 'Weekly traffic plan', 'Guardrail report'],
    frontier: 'Revenue vs retention',
    frontierMode: 'Measured retention model',
    frontierPickChannel: 'Pick your channel in settings to forecast your own inventory. The chart projects revenue for your channel only; competing programmes feed the retention model, never the revenue forecast.',
    frontierComputing: 'Computing your channel forecast. This runs a real optimisation in the background and appears here once ready; refresh in a moment.',
    heatmap: 'Daypart inventory heatmap',
    heatmapEmpty: 'No daypart heatmap data yet',
    opportunity: 'Revenue opportunity',
    compliance: 'Compliance ledger',
    activeRules: 'active rules',
    compliant: 'Compliant',
    atRisk: 'At risk',
    none: 'None',
    settingsTitle: 'Market and policy settings',
    settingsIntro: 'Controls are operational defaults, not hard-coded law. Update the profile when regulation, rate cards, or broadcaster policy changes.',
    saveSettings: 'Save changes',
    saving: 'Saving...',
    saved: 'Saved',
    saveFailed: 'Save failed',
    unsavedChanges: 'You have unsaved changes',
    noChanges: 'All changes saved',
    profile: 'Profile',
    source: 'Source',
    effectiveDate: 'Effective date',
    language: 'Language',
    hebrew: 'Hebrew',
    english: 'English',
    maxAdMinutes: 'Max ad minutes per hour',
    maxBreaks: 'Max breaks per hour',
    spacing: 'Minimum break spacing',
    retentionFloor: 'Retention floor',
    dailyCap: 'Daily ad-minute cap',
    protectedMax: 'Protected content max ad minutes',
    protectedTypes: 'Protected programme types',
    sponsorships: 'Sponsorships enabled',
    gold: 'Gold breaks enabled',
    approval: 'Manual approval required',
    riskCaution: 'Caution level',
    riskCautionHelp: 'How conservative the money on screen is. Every break carries a measured uncertainty range around its retention cost: at 0 the numbers use the central estimate (the likely case); sliding up prices each break closer to the worst plausible cost in its range, so the reported net is a cautious promise you can commit to. On the current data this changes only the reported numbers, never which breaks are scheduled.',
    riskCautionSetting: 'Default caution level',
    retentionCostTitle: 'Retention cost confidence',
    retentionCostIntro: 'How trustworthy the retention cost is behind each segment in this plan.',
    retentionCostConfidence: { low: 'Low', medium: 'Medium', high: 'High' },
    retentionCostAssumption: 'assumption',
    retentionCostInterval: 'Uncertainty range',
    retentionCostBreaks: 'real breaks',
    retentionCostNoInterval: 'No uncertainty range measured',
    retentionCostPoint: 'Likely value',
    retentionCostUsed: 'Value used',
  },
  he: {
    nav: {
      Today: 'היום',
      Plan: 'תכנון',
      Broadcast: 'שידור',
      Commercial: 'מסחרי',
      Sources: 'מקורות',
      Governance: 'ממשל וכללים',
      History: 'היסטוריה',
      Model: 'מודל החברה',
      Overview: 'סקירה',
      Optimizer: 'אופטימייזר',
      Schedule: 'לוח שידורים',
      Inventory: 'מלאי',
      'Break Library': 'ספריית ברייקים',
      Campaigns: 'קמפיינים',
      Forecasts: 'תחזיות',
      Calendar: 'לוח אירועים',
      Reports: 'דוחות',
      Data: 'נתונים',
      Advertisers: 'מפרסמים',
      Agencies: 'סוכנויות',
      Pricing: 'תמחור',
      Overrides: 'עקיפות',
      Assistant: 'מבט, עוזר תפעולי',
      Versions: 'שחזור שינויים',
      Settings: 'הגדרות',
    },
    workspace: 'ניהול הכנסות מפרסום',
    operatorRole: 'Revenue Ops',
    optimizer: 'אופטימייזר',
    scenario: 'תרחיש',
    scenarios: ['מאוזן', 'מקסום הכנסה', 'הגנת שימור'],
    compare: 'השוואה',
    // Starts with a Hebrew anchor on purpose: a label whose first strong
    // character is Latin resolves LTR and the chip read "חי API", reversed.
    liveApi: 'ה־API חי',
    checkingApi: 'בודק חיבור ל־API',
    snapshot: 'אין חיבור ל־API',
    partialData: 'חלק מהנתונים לא נטענו',
    data: 'נתונים',
    dataUpdated: 'עודכן',
    refresh: 'רענון',
    notifications: 'התראות',
    runOptimization: 'הרצת אופטימיזציה',
    loading: 'טוען סביבת Kairos',
    apiUnavailable: 'ה־API לא זמין. חלק מהנתונים לא נטענו.',
    // הכותרת מדברת באופק העבודה של המפעיל: שבוע התכנון (summary.week מה-API).
    // התאריכים המדויקים מפורטים בשורת המשנה של האריח ומתחת לרצועה.
    metrics: ['הכנסה שבועית צפויה', 'שימור צופים בברייקים', 'דקות פרסום בשבוע', 'סיכון שימור'],
    // Masculine forms: they qualify סיכון (the tile is labeled 'סיכון שימור').
    risk: { High: 'גבוה', Medium: 'בינוני', Low: 'נמוך', Unknown: 'לא ידוע' },
    toolbar: ['תצוגת גריד', 'ציר זמן', 'רצועות שידור', 'מלאי', 'תוכניות', 'ברייקים', 'מדדים'],
    canvas: 'משטח תכנון שידור',
    channelProgram: 'ערוץ / תוכנית',
    selectedBreak: 'ברייק נבחר',
    pending: 'ממתין',
    approved: 'מאושר',
    detail: ['הכנסת תוכנית', 'שימור בתוכנית', 'משך', 'חסויות'],
    guardrails: 'בקרות',
    recommendation: 'המלצה',
    approve: 'אישור',
    reject: 'דחייה',
    applySimilar: 'אישור דומים',
    export: 'ייצוא',
    exportOptions: ['פרטי ברייק', 'תוכנית טראפיק שבועית', 'דוח בקרות'],
    frontier: 'הכנסה מול שימור',
    frontierMode: 'מודל שימור מדוד',
    frontierPickChannel: 'בחרו את הערוץ שלכם בהגדרות כדי לחזות את המלאי שלכם בלבד. הגרף מציג תחזית הכנסה לערוץ שלכם בלבד; תוכניות מתחרות מזינות את מודל השימור, לעולם לא את תחזית ההכנסה.',
    frontierComputing: 'מחשבים את תחזית הערוץ שלכם. זוהי אופטימיזציה אמיתית שרצה ברקע ותופיע כאן ברגע שתהיה מוכנה; רעננו עוד רגע.',
    heatmap: 'מפת חום לפי רצועת שידור',
    heatmapEmpty: 'אין עדיין נתוני מפת חום לפי רצועה',
    opportunity: 'פוטנציאל הכנסה',
    compliance: 'יומן תאימות',
    activeRules: 'כללים פעילים',
    compliant: 'תקין',
    atRisk: 'דורש בדיקה',
    none: 'אין',
    settingsTitle: 'הגדרות שוק ומדיניות',
    settingsIntro: 'אלה ברירות מחדל תפעוליות, לא חוק קשיח בקוד. מעדכנים את הפרופיל כשהרגולציה, מחירונים או מדיניות הערוץ משתנים.',
    saveSettings: 'שמירת שינויים',
    saving: 'שומר...',
    saved: 'נשמר',
    saveFailed: 'השמירה נכשלה',
    unsavedChanges: 'יש לכם שינויים שלא נשמרו',
    noChanges: 'כל השינויים נשמרו',
    profile: 'פרופיל',
    source: 'מקור',
    effectiveDate: 'תאריך תחולה',
    language: 'שפה',
    hebrew: 'עברית',
    english: 'אנגלית',
    maxAdMinutes: 'מקסימום דקות פרסום בשעה',
    maxBreaks: 'מקסימום ברייקים בשעה',
    spacing: 'מרווח מינימלי בין ברייקים',
    retentionFloor: 'רף שימור',
    dailyCap: 'תקרת דקות פרסום יומית',
    protectedMax: 'דקות פרסום מקסימליות בתוכן מוגן',
    protectedTypes: 'סוגי תוכן מוגן',
    sponsorships: 'חסויות פעילות',
    gold: 'ברייקי זהב פעילים',
    approval: 'נדרש אישור ידני',
    riskCaution: 'רמת זהירות',
    riskCautionHelp: 'כמה שמרניים המספרים שעל המסך. לכל ברייק יש טווח אי-ודאות מדוד סביב עלות השימור שלו: ב-0 המספרים מחושבים לפי האומדן המרכזי (התרחיש הסביר), וככל שמעלים, כל ברייק מתומחר קרוב יותר לעלות הגרועה הסבירה בטווח שלו, כך שהנטו המדווח הוא הבטחה זהירה שאפשר להתחייב עליה. בנתונים הנוכחיים זה משנה רק את המספרים המדווחים, אף פעם לא את הברייקים שמשובצים.',
    riskCautionSetting: 'רמת זהירות כברירת מחדל',
    retentionCostTitle: 'מהימנות עלות השימור',
    retentionCostIntro: 'עד כמה אפשר לסמוך על עלות השימור שמאחורי כל סגמנט בתוכנית הזו.',
    retentionCostConfidence: { low: 'נמוכה', medium: 'בינונית', high: 'גבוהה' },
    retentionCostAssumption: 'הנחה',
    retentionCostInterval: 'טווח אי-ודאות',
    retentionCostBreaks: 'ברייקים אמיתיים',
    retentionCostNoInterval: 'לא נמדד טווח אי-ודאות',
    retentionCostPoint: 'הערך הסביר',
    retentionCostUsed: 'הערך שנעשה בו שימוש',
  },
};
