// Field names, in the language a reviewer reads.
//
// The parameter schemas name their fields for the machine: `share_threshold_percent`,
// `re_rating_rule`, `cure_form`. Printing one of those beside an input is the
// raw-internal-key defect this product has already paid for twice, so every
// field the corpus documents actually carry is named here in both languages, and
// a key with no entry falls back to its own name with the underscores opened out
// — visibly unpolished, which is the point: it is a missing translation to
// notice, not a label to accept.
//
// `long: true` marks a field whose value is a sentence from the document rather
// than a token, so the editor gives it a text area instead of a single line.

export const PARAM_LABELS = {
  // money and rate structures
  amount: { he: 'סכום', en: 'Amount' },
  currency: { he: 'מטבע', en: 'Currency' },
  basis: { he: 'בסיס', en: 'Basis' },
  base: { he: 'הבסיס לחישוב', en: 'What it is calculated on' },
  cpp: { he: 'עלות לנקודת רייטינג', en: 'Cost per rating point' },
  cap: { he: 'תקרה', en: 'Cap' },
  percent: { he: 'שיעור באחוזים', en: 'Rate, in percent' },
  price: { he: 'מחיר', en: 'Price' },
  price_per_airing: { he: 'מחיר לשידור', en: 'Price per airing' },
  threshold: { he: 'מהיקף של', en: 'From a volume of' },
  discount_percent: { he: 'שיעור ההנחה', en: 'Discount rate' },
  tiers: { he: 'מדרגות', en: 'Tiers' },
  mechanics: { he: 'אופן החלת המדרגות', en: 'How the tiers apply' },
  factor: { he: 'מקדם', en: 'Multiplier' },
  coefficient: { he: 'מקדם', en: 'Coefficient' },
  surcharge_percent: { he: 'תוספת באחוזים', en: 'Surcharge, in percent' },
  premium_percent: { he: 'תוספת באחוזים', en: 'Premium, in percent' },
  bundle_discount_percent: { he: 'הנחת החבילה באחוזים', en: 'Bundle discount, in percent' },
  award_discount_percent: { he: 'ההטבה באחוזים', en: 'Award, in percent' },
  rate_percent: { he: 'שיעור הצבירה', en: 'Accrual rate' },
  fee_percent: { he: 'החיוב באחוזים', en: 'Fee, in percent' },
  min_percent: { he: 'לפחות, באחוזים', en: 'At least, in percent' },
  max_percent: { he: 'לכל היותר, באחוזים', en: 'At most, in percent' },
  share_percent: { he: 'הנתח באחוזים', en: 'Share, in percent' },
  share_threshold_percent: { he: 'הנתח הנדרש באחוזים', en: 'Share to reach, in percent' },
  target_percent: { he: 'היעד באחוזים', en: 'Target, in percent' },
  tolerance_percent: { he: 'סטייה מותרת באחוזים', en: 'Tolerance, in percent' },
  spend_basis: { he: 'ההיקף שעליו נמדד', en: 'Spend the figure is measured on' },
  fixed_prices: { he: 'מחירים קבועים', en: 'Fixed prices' },
  rounding_rule: { he: 'כלל העיגול', en: 'Rounding rule', long: true },

  // scope and identity
  advertiser: { he: 'המפרסם', en: 'Advertiser' },
  agency: { he: 'הסוכנות', en: 'Agency' },
  counterparty_type: { he: 'סוג הצד להסכם', en: 'Kind of counterparty' },
  direct_client: { he: 'לקוח ישיר', en: 'Direct client' },
  signatories: { he: 'החותמים', en: 'Signatories' },
  represented_advertisers: { he: 'מפרסמים מיוצגים', en: 'Advertisers represented' },
  included_brands: { he: 'מותגים בהיקף', en: 'Brands included' },
  level: { he: 'רמת ההסכם', en: 'Agreement level' },
  parent_agreement: { he: 'ההסכם שמעליו', en: 'The agreement above it', long: true },
  base_agreement: { he: 'ההסכם שמתוקן', en: 'The agreement being amended' },
  modifies: { he: 'הסעיפים המשתנים', en: 'Clauses it changes' },
  component: { he: 'מרכיב', en: 'Component' },
  components: { he: 'מרכיבי החבילה', en: 'Bundle components' },
  in_product: { he: 'מתוכנן ונספר במערכת', en: 'Planned and counted here' },
  programme: { he: 'התוכנית', en: 'Programme' },
  slot_note: { he: 'תיאור השיבוץ', en: 'Slot description' },
  daypart: { he: 'הרצועה', en: 'Daypart' },
  daypart_bounds: { he: 'שעות הרצועה', en: 'Daypart hours' },
  start: { he: 'משעה', en: 'From' },
  end: { he: 'עד שעה', en: 'To' },

  // windows and dates
  starts_on: { he: 'תחילה', en: 'Starts on' },
  ends_on: { he: 'סיום', en: 'Ends on' },
  effective_on: { he: 'נכנס לתוקף', en: 'Takes effect on' },
  auto_renewal: { he: 'חידוש אוטומטי', en: 'Renews automatically' },
  renewal_notice_days: { he: 'ימי הודעה לפני חידוש', en: 'Notice days before renewal' },
  window: { he: 'החלון', en: 'Window' },
  window_note: { he: 'תיאור החלון', en: 'The window, as written', long: true },
  applies_to: { he: 'חל על', en: 'Applies to', long: true },
  period: { he: 'התקופה', en: 'Period' },
  period_label: { he: 'התקופה', en: 'Period' },
  notice_days: { he: 'ימי הודעה', en: 'Notice days' },
  days_before_air: { he: 'ימים לפני השידור', en: 'Days before air' },
  expiry: { he: 'מתי פג', en: 'When it expires', long: true },
  delivery_window: { he: 'חלון האספקה', en: 'Delivery window', long: true },
  cure_window: { he: 'חלון ההשלמה', en: 'Cure window', long: true },
  settlement_cycle: { he: 'מחזור ההתחשבנות', en: 'Settlement cycle', long: true },
  billing_cycle: { he: 'מחזור החיוב', en: 'Billing cycle', long: true },
  cadence: { he: 'תכיפות', en: 'How often' },
  checkpoints: { he: 'נקודות ביקורת', en: 'Checkpoints', long: true },

  // measurement
  audience: { he: 'קהל היעד', en: 'Audience' },
  audience_basis: { he: 'בסיס הקהל', en: 'Audience basis', long: true },
  points: { he: 'נקודות רייטינג', en: 'Rating points' },
  vintage: { he: 'גרסת הנתון', en: 'Vintage of the figure', long: true },
  source: { he: 'המקור', en: 'Source' },
  source_order: { he: 'סדר הקדימות בין מקורות', en: 'Order of authority between sources', long: true },
  final_rule: { he: 'איזה נתון סופי', en: 'Which figure is final', long: true },
  grain: { he: 'גרעין המדידה', en: 'Measurement grain', long: true },
  measurement_basis: { he: 'בסיס המדידה', en: 'Measurement basis', long: true },
  counting_method: { he: 'שיטת הספירה', en: 'Counting method' },
  denominator_source: { he: 'מקור המכנה', en: 'Where the denominator comes from', long: true },
  application_order: { he: 'סדר החלת התנאים', en: 'Order the terms apply in', long: true },

  // placement
  positions: { he: 'מיקומים', en: 'Positions' },
  preferred_positions: { he: 'מיקומים מועדפים', en: 'Preferred positions' },
  top_and_tail: { he: 'פותח וסוגר', en: 'Opens and closes the break' },
  allowed_lengths_seconds: { he: 'אורכים מותרים בשניות', en: 'Allowed lengths, in seconds' },
  length_seconds: { he: 'אורך בשניות', en: 'Length, in seconds' },
  base_length_seconds: { he: 'אורך תשדיר הבסיס בשניות', en: 'Base spot length, in seconds' },
  notice_length_seconds: { he: 'אורך הודעת החסות בשניות', en: 'Sponsor announcement length, in seconds' },
  airings: { he: 'מספר שידורים', en: 'Airings' },
  count: { he: 'כמות', en: 'Count' },
  unit: { he: 'היחידה', en: 'Unit' },
  mode: { he: 'סוג ההגבלה', en: 'Kind of restriction' },
  hard: { he: 'קשיח', en: 'Hard rule' },
  radius: { he: 'טווח ההרחקה', en: 'Exclusion radius' },
  excluded_content: { he: 'תוכן שיש להרחיק ממנו', en: 'Content to keep away from' },
  target_content: { he: 'התוכן שאליו נצמדים', en: 'Content it is bought beside' },
  break_relation: { he: 'איזה מקבץ', en: 'Which break', long: true },
  category: { he: 'הקטגוריה', en: 'Category' },
  exclusivity_scope: { he: 'היקף הבלעדיות', en: 'Scope of exclusivity', long: true },
  separation_unit: { he: 'יחידת ההפרדה', en: 'Separation unit' },
  separation_quantity: { he: 'כמות ההפרדה', en: 'Separation quantity' },
  first_refusal: { he: 'זכות סירוב ראשונה', en: 'First refusal' },
  qc_gate: { he: 'שער אישור שידור', en: 'Clearance gate' },
  allowed: { he: 'מותר', en: 'Allowed' },

  // obligations, cures and settlement
  cure_form: { he: 'צורת ההשלמה', en: 'Form of cure' },
  quality_rule: { he: 'כלל האיכות', en: 'Quality rule', long: true },
  quality_note: { he: 'הערת איכות', en: 'Quality note', long: true },
  valuation_basis: { he: 'בסיס ההערכה', en: 'Valuation basis', long: true },
  treatment: { he: 'הטיפול', en: 'Treatment' },
  banking_cap: { he: 'גבול הצבירה', en: 'Banking cap', long: true },
  accruals: { he: 'כללי צבירה', en: 'Accrual rules' },
  trigger: { he: 'מה מפעיל', en: 'What triggers it', long: true },
  trigger_note: { he: 'מה מפעיל', en: 'What triggers it', long: true },
  utilisation: { he: 'אופן הניצול', en: 'How it may be used', long: true },
  re_rating_rule: { he: 'כלל החישוב מחדש', en: 'How it is recalculated', long: true },
  true_up_form: { he: 'צורת ההשלמה בחריגה', en: 'Form of true-up on breach', long: true },
  remedy_form: { he: 'הסעד', en: 'The remedy', long: true },
  qualifying_events: { he: 'מה מקים את הסעיף', en: 'What qualifies', long: true },
  qualifying_terms: { he: 'מה מזכה', en: 'What qualifies for it', long: true },
  qualification: { he: 'תנאי הזכאות', en: 'Qualification', long: true },
  relief: { he: 'ההקלה', en: 'The relief', long: true },
  award_note: { he: 'מה מוענק', en: 'What is awarded', long: true },
  survival: { he: 'מה שורד את הסיום', en: 'What survives the end' },
  premium_note: { he: 'תוספת המחיר', en: 'What it costs extra', long: true },
  discount_blackout: { he: 'חסימת הנחה', en: 'No discount at all' },

  // process and documents
  summary: { he: 'תקציר הסעיף', en: 'What the clause says', long: true },
  terms: { he: 'התנאים', en: 'Terms', long: true },
  notes: { he: 'הערות', en: 'Notes', long: true },
  note: { he: 'הערה', en: 'Note', long: true },
  rule: { he: 'הכלל', en: 'Rule', long: true },
  rules: { he: 'הכללים', en: 'Rules' },
  rows: { he: 'שורות', en: 'Rows' },
  windows: { he: 'מדרגות', en: 'Bands' },
  entries: { he: 'ההגדרות', en: 'Definitions' },
  term: { he: 'המונח', en: 'Term' },
  definition: { he: 'ההגדרה', en: 'Definition', long: true },
  report: { he: 'הדוח', en: 'Report', long: true },
  reports: { he: 'הדוחות', en: 'Reports' },
  label: { he: 'תיאור', en: 'Label' },
  verbatim: { he: 'לשון הסעיף', en: 'The clause, as written', long: true },
  winner: { he: 'הגובר', en: 'Wins' },
  loser: { he: 'הנדחה', en: 'Loses' },
  scope_note: { he: 'היקף התחולה', en: 'Scope note', long: true },
  form: { he: 'צורת ההתחשבנות', en: 'Form of settlement' },
  splits: { he: 'פיצולים', en: 'Splits' },

  // basis vocabulary, reused as select labels
  gross: { he: 'ברוטו', en: 'Gross' },
  net_of_commission: { he: 'נטו לאחר עמלה', en: 'Net of commission' },
  net_of_discount: { he: 'נטו לאחר הנחות', en: 'Net of discounts' },
  ratecard: { he: 'לפי מחירון', en: 'At rate card' },
  unstated: { he: 'לא נקבע במסמך', en: 'Not stated in the document' },
};

export function paramLabel(key, locale) {
  const entry = PARAM_LABELS[String(key || '')];
  if (entry) return locale === 'he' ? entry.he : entry.en;
  return String(key || '').replace(/_/g, ' ');
}
