name: Publish to PyPI/TestPyPI

inputs:
  repository_url:
    description: The URL of the PyPI repository (PyPI or TestPyPI).
    required: true
  environment_name:
    description: The name of the environment (pypi or testpypi).
    required: true

runs:
  using: "composite"
  steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: ${{ inputs.repository_url }}
        verbose: true