name: CI  # For unit tests and build

on:
  push:
    branches:
      - '**'

env:
  USE_PYTHON_VERSION: "3.11"

jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      max-parallel: 2
      matrix:
        python-version: ["3.11", "3.12"]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.python-version }}
      cancel-in-progress: true

    name: pytest (python-${{ matrix.python-version }})

    steps:
      - uses: actions/checkout@v3

      # Install deps
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          # Uncomment to cache of pip dependencies (if tests too slow)
          cache: pip
          cache-dependency-path: '**/pyproject.toml'

      - run: pip --version
      - run: pip install -e .[dev] --config-settings editable_mode=strict
      - run: pip freeze

      # Run tests (in parallel)
      - name: Run core tests
        run: pytest -vv -n auto

  build:
    name: Build distribution
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build
        with:
          python_version: ${{ env.USE_PYTHON_VERSION }}
