name: Unittests & Auto-publish

# Allow to trigger the workflow manually (e.g. when deps changes) or on tag pushes.
on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'  # Trigger only on tags starting from 'v'.
  workflow_dispatch:
    inputs:
      publish_to_pypi:
        description: 'Publish to PyPI?'
        required: false
        type: boolean
        default: false
      publish_to_testpypi:
        description: 'Publish to TestPyPI?'
        required: false
        type: boolean
        default: false

jobs:
  pytest-job:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v3

    # Install deps
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        # Uncomment to cache of pip dependencies (if tests too slow)
        cache: pip
        cache-dependency-path: '**/pyproject.toml'

    - run: pip --version
    - run: pip install -e .[dev] --config-settings editable_mode=strict
    - run: pip freeze

    # Run tests (in parallel)
    - name: Run core tests
      run: pytest -vv -n auto

  build:
    name: Build distribution
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: >-
      Publish Python distribution to PyPI
    # Check if it's a tag push or the `publish_to_pypi` workflow is selected in a manual trigger.
    if: >
      (github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/'))
      || (github.event_name == 'workflow_dispatch'
          && github.event.inputs.publish_to_pypi == 'true')
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/google-meridian
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true

  publish-to-testpypi:
    name: Publish Python distribution to TestPyPI
    # Check if the `publish_to_testpypi` workflow is selected in a manual trigger.
    if: >
      (github.event_name == 'workflow_dispatch'
        && github.event.inputs.publish_to_testpypi == 'true')
    needs:
    - build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/meridian

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        verbose: true