"""A session for the competitor's schedule that renews itself.

The publication needs a signed-in session and answers 401 to anyone else, and
that session is short: measured, ``sfp_access`` is issued with about twenty-one
hours of life and the server ends it sooner than that. A pull that runs every
morning would therefore fail every morning, which is how a feature like this
quietly stops working a week after it ships.

WHAT WAS MEASURED, AND WHAT IT RULES OUT
----------------------------------------
* There is NO bearer token to keep. The application stores nothing in
  ``localStorage`` but table column widths, and the only cookie JavaScript can
  see is ``XSRF-TOKEN``. The session itself is ``sfp_access``, HttpOnly, which a
  page script cannot read — but the debugging protocol can, which is what makes
  this possible at all.
* The login cannot be driven by URL. ``/api/auth/google?env=prod`` answers
  ``{"success":false,"message":"Code challenge is missing."}``: the flow is
  Google OAuth **with PKCE**, so the verifier is generated by the application and
  only the application can complete the handshake. Any attempt to hand-roll the
  OAuth round trip is building a second, weaker copy of it.
* So the renewal is: let the application do its own PKCE, in a browser profile
  where GOOGLE is still signed in. Measured end to end — clicking the app's own
  control returned a fresh session in ten seconds with no password, because a
  Google session outlives a Kway one by months.

THE SHAPE THIS GIVES
--------------------
One long-lived thing (the Google session in a dedicated profile) renews one
short-lived thing (the Kway session) on demand, and the short-lived thing is
what every pull uses. Nothing here stores a password, and the profile lives
outside this repository.

WHEN A HUMAN IS UNAVOIDABLE
---------------------------
Google will eventually challenge — a new device, a policy change, a revoked
grant. That is not a failure to paper over: :func:`renew` reports
``needs_human`` with the exact one step to take, and the caller says so out
loud. What must never happen is a silent failure that leaves a stale schedule
looking fresh, so this module never returns a session it did not verify.
"""

from __future__ import annotations

import json
import os
import subprocess
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

API = "https://api.kway.co.il/api"
APP_LOGIN = "https://app.kway.co.il/auth/login"
DASHBOARD = "https://app.kway.co.il/dashboard"
EPG_PATH = "/keshetliveschedule"

# The control the application renders for its own login. A span, not a button —
# so the click goes to its nearest clickable ancestor when it has one.
LOGIN_SELECTOR = ".continue-with-google"

# Where the browser profile that holds the Google session lives. Deliberately
# NOT in this repository: it carries a live login, and a repository is the wrong
# place for one. Overridable, because a server will not keep it where a laptop
# does.
PROFILE_ENV = "KAIROS_KWAY_PROFILE"
DEFAULT_PROFILE = Path.home() / ".kairos" / "kway-profile"

# Which account to continue as when Google asks. Not hard-coded: this engine
# will be run by somebody who is not the person who built it.
ACCOUNT_ENV = "KAIROS_KWAY_ACCOUNT"

# The session is kept in the OS keychain rather than a dotfile. It is a live
# credential; a file is one `cat` away from a screenshot.
KEYCHAIN_SERVICE = "kairos-kway-session"


class SessionUnavailable(RuntimeError):
    """No usable session, with a reason a person can act on."""


@dataclass
class Session:
    """A verified session: the cookies to send, and when it was proven alive."""

    cookies: dict[str, str]
    verified_at: datetime
    account: dict[str, Any] = field(default_factory=dict)

    @property
    def cookie_header(self) -> str:
        return "; ".join(f"{name}={value}" for name, value in self.cookies.items())

    def headers(self) -> dict[str, str]:
        head = {"Cookie": self.cookie_header, "Accept": "application/json"}
        # Laravel refuses an unsafe method without the token it handed out; the
        # EPG read does not need it, but a caller doing anything else does.
        token = self.cookies.get("XSRF-TOKEN")
        if token:
            head["X-XSRF-TOKEN"] = token
        return head

    def age_hours(self, now: Optional[datetime] = None) -> float:
        return ((now or datetime.now(timezone.utc)) - self.verified_at).total_seconds() / 3600.0


# ------------------------------------------------------------------ storage

def _keychain(action: str, *args: str, stdin: Optional[str] = None) -> Optional[str]:
    try:
        done = subprocess.run(
            ["security", action, *args],
            input=stdin, capture_output=True, text=True, timeout=15,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    return done.stdout if done.returncode == 0 else None


def save_session(session: Session, *, account_label: str = "kway") -> bool:
    """Keep the session in the login keychain. Returns whether it was kept."""
    blob = json.dumps({
        "cookies": session.cookies,
        "verified_at": session.verified_at.isoformat(),
        "account": session.account,
    }, ensure_ascii=False)
    _keychain("delete-generic-password", "-s", KEYCHAIN_SERVICE, "-a", account_label)
    return _keychain(
        "add-generic-password", "-s", KEYCHAIN_SERVICE, "-a", account_label,
        "-w", blob, "-U",
    ) is not None


def load_session(*, account_label: str = "kway") -> Optional[Session]:
    raw = _keychain("find-generic-password", "-s", KEYCHAIN_SERVICE,
                    "-a", account_label, "-w")
    if not raw:
        return None
    try:
        data = json.loads(raw.strip())
        return Session(
            cookies=dict(data["cookies"]),
            verified_at=datetime.fromisoformat(data["verified_at"]),
            account=data.get("account") or {},
        )
    except Exception:  # noqa: BLE001 - an unreadable secret is no secret
        return None


# ------------------------------------------------------------- verification

def alive(session: Session, *, timeout: float = 20.0) -> bool:
    """Is this session actually accepted right now?

    Asked of the server, never inferred from a cookie's expiry: the measured
    gap between the two is the whole reason this module exists — the cookie
    still looked valid for hours after the server had ended the session.
    """
    import urllib.error
    import urllib.request

    request = urllib.request.Request(f"{API}/user", headers=session.headers())
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            return response.status == 200
    except urllib.error.HTTPError:
        return False
    except Exception:  # noqa: BLE001 - unreachable is not the same as rejected,
        return False   # but neither is a session this module will hand out.


def fetch_epg(session: Session, *, timeout: float = 45.0) -> Any:
    """The publication, with a live session. Raises when it is not."""
    import urllib.error
    import urllib.request

    request = urllib.request.Request(f"{API}{EPG_PATH}", headers=session.headers())
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            return json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        if exc.code == 401:
            raise SessionUnavailable("the session was rejected by the publication") from exc
        raise


# ------------------------------------------------------------------ renewal

def _chrome_binary() -> str:
    return os.environ.get(
        "KAIROS_CHROME",
        "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    )


def profile_path() -> Path:
    return Path(os.environ.get(PROFILE_ENV, "").strip() or DEFAULT_PROFILE)


def account_hint() -> str:
    """Which account this renews, so a chooser is answered and not guessed at.

    Taken from the environment, then from whatever the last verified session
    said it was. A profile holding one Google account needs neither; a profile
    that later holds two needs this, and the day it starts mattering is not a
    day anyone will be watching.
    """
    named = os.environ.get(ACCOUNT_ENV, "").strip()
    if named:
        return named
    stored = load_session()
    return str((stored.account or {}).get("email") or "") if stored else ""


def renew(*, budget_seconds: float = 90.0, port: int = 9444,
          headless: bool = True) -> dict[str, Any]:
    """Let the application renew its own session, and take the cookies.

    Drives the app's own login control so the PKCE handshake is performed by the
    code that owns it, answers Google's account chooser with a NAMED account,
    and stops at anything only a person can settle — a password, a second
    factor, a grant of access — reporting the one step to take.

    Nothing here is timed or slept through. The flow is watched, and each state
    it can be in is answered or reported, because the failure this replaced was
    a flow sitting on an unanswered page until a timeout expired and blamed the
    network.
    """
    from kairos.model import kway_browser

    return kway_browser.renew_via_profile(
        chrome=_chrome_binary(),
        profile=profile_path(),
        headless=headless,
        budget_seconds=budget_seconds,
        port=port,
        account_hint=account_hint() or None,
    )


def current(*, allow_renew: bool = True) -> tuple[Optional[Session], dict[str, Any]]:
    """The session to use now: stored if it still works, renewed if it does not.

    Returns ``(session, status)``. ``session`` is None only when this module
    could not obtain a verified one, and ``status`` always says why in a
    sentence a person can act on.
    """
    stored = load_session()
    if stored is not None and alive(stored):
        return stored, {
            "state": "reused",
            "age_hours": round(stored.age_hours(), 1),
            "reason": "the stored session is still accepted",
        }
    if not allow_renew:
        return None, {
            "state": "expired",
            "reason": "the stored session is no longer accepted and renewal was not permitted",
        }
    outcome = renew()
    if outcome.get("renewed"):
        session = Session(
            cookies=outcome["cookies"],
            verified_at=datetime.now(timezone.utc),
            account=outcome.get("account") or {},
        )
        save_session(session)
        return session, {
            "state": "renewed",
            "seconds": outcome.get("seconds"),
            "reason": "the session was renewed from the stored browser profile without a person",
        }
    return None, {
        "state": "needs_human" if outcome.get("needs_human") else "failed",
        "reason": outcome.get("reason", "the session could not be renewed"),
        "do_this": outcome.get("do_this", ""),
    }
